### ISSUE TITLE
Line 23 problem

### ISSUE THREAD

**Issue by Puggylive** [Sheldenshi/ERC20Deflationary#9]
I get this probleme when I try to launch the contract any tips? ^^

![Capture2](https://user-images.githubusercontent.com/84539517/120941694-fe40a700-c6f1-11eb-93ab-55494aaab140.PNG)

**Comment by Puggylive** [comment]
![image](https://user-images.githubusercontent.com/84539517/120941716-36e08080-c6f2-11eb-8b76-4203955dd06a.png)

**Comment by Sheldenshi** [comment]
I updated the READEME page
